sudo: false
language: java

jdk:
  - openjdk8

before_install:
  - cd AwgenShell

cache:
  apt: true
  directories:
    - ~/.m2

install: true
script:
  - mvn test -B;

after_success:
  - mvn jacoco:report coveralls:report
